on: pull_request
name: PR Review
jobs:
  test-composer-files:
    name: Validate composer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: ctype, dom, iconv, json, zip, gd, soap
          coverage: none
          tools: composer:v2
      - name: Validate composer files
        run: |
          composer validate composer.json

  phpcs:
    name: PHP - Check Coding Standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: ctype, dom, iconv, json, zip, gd, soap
          coverage: none
          tools: composer:v2
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: PHPCS
        run: |
          composer coding-standards-check

  yarncs:
    name: Yarn - Check Coding Standards (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '15' ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: |
          yarn install
          yarn coding-standards-check

  site-install:
    name: Drupal install test
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.4
        env:
          MYSQL_USER: db
          MYSQL_PASSWORD: db
          MYSQL_DATABASE: db
          MYSQL_ROOT_PASSWORD: db
        options:
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@master
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: ctype, dom, iconv, json, zip, gd, soap
          coverage: none
          tools: composer:v2
      - name: Write 'settings.local.php'
        run: |
          cat <<'EOF' > web/sites/default/settings.local.php
          <?php
          $databases['default']['default'] = [
            'database' => 'db',
            'username' => 'db',
            'password' => 'db',
            'host' => '127.0.0.1',
            'port' => '${{ job.services.mysql.ports['3306'] }}',
            'driver' => 'mysql',
            'prefix' => '',
          ];
          EOF
      - name: Echo 'settings.local.php'
        run: |
          echo
          <?php
          $databases['default']['default'] = [
            'database' => 'db',
            'username' => 'db',
            'password' => 'db',
            'host' => '127.0.0.1',
            'port' => '${{ job.services.mysql.ports['3306'] }}',
            'driver' => 'mysql',
            'prefix' => '',
          ];
          EOF
      - name: Install Drupal with config
        run: |
          composer install --no-dev --optimize-autoloader
          vendor/bin/drush --yes site:install os2loop --existing-config
